### ISSUE TITLE
barcode lenght is shorter than my pattern.

### ISSUE THREAD

**Issue by mortunco** [LaoZZZZZ/bartender-1.1#69]
Hi,

I was asked to extract UMIs from given reads. Our sequences should be in the following format where 5' and 3' sequences are shown. T in umi sequence is constant. 

> AGATTGATCTAGAGCATGCACCGGACACTCTTTCCCTACACGACGCTCTTCCGATCT**NNNNNTNNNN**TCCATGAGACTCCTGAGTCAGAGGCAAAGGCTTTTACTGCTCACAGCTTAGCAGACAGCATGAGGTTCATGTTCACAT

I ran extractor like below.

```bartender_extractor_com -f ../UMI_r2.fastq -p GATCT[5]T[4]TCCAT -o r2_results_1.1 -d both```

However in the resulting barcode file all of the sequences are always 9 bp. where shouldnt it be 10? since my umi sequence is NNNNNTNNNN

Because of the 9 bps problem, i couldn't run the umi mode as well.

A little guidance would totally be appreciated.

Best regards,

Tunc.

**Comment by mortunco** [comment]
Barcode file head.
```[tmorova@xavier3 bartender-1.1]$ head r2_results_1.1_barcode.txt
CTGATTCTT,5
TCGATACCG,9
TCTTCGTAT,13
TTTCGGGTA,17
CAAGTTTTT,21
TTCTTAGTG,25
TCTAAGTTT,29
TTTATACCT,33
GTTTTTCTT,37
ATCGACTTC,41 ```

**Comment by LaoZZZZZ** [comment]
Hi Mortunco,

Bartender will remove those constant letters specified from the pattern as those constant part does not help with the clustering step except make clustering slower.  Would you please explain more why UMI mode is not feasible because of this? Since Bartender only support the case that UMI locates at fix position with fix length, is this restriction prevent you using UMI mode?

Thanks for using Bartender. Any feedback on the Bartender is appreciated.
Best,
Lu

**Comment by LaoZZZZZ** [comment]
The thread has been inactive for about 5 month. Closing it. Feel free to open it if you still have problem with it.
