### ISSUE TITLE
Maximum cluster distance parameter (-d) does not work

### ISSUE THREAD

**Issue by djross22** [LaoZZZZZ/bartender-1.1#83]
I don't know if anyone is still maintaining  this repo, but I was looking at the details of some clustering results with a new dataset, and I noticed that the clustering algorithm is merging sequences with a Hamming distance greater than the -d parameter.

With the -d parameter set to 3, I found one cluster that contains sequences with Hamming distance up to 6 from the cluster center.
The command line call I'm using is:
```
python ~/bartender-1.1/bartender_single_com -f 2023-09-26_test_12_lintags.txt -o 2023-09-26_test -c 100 -z 5 -l 5 -s 1 -t 4 -d 3
```

I have a relatively small barcode data file that reproduces the problem, but it is still too big to attach here (200 MB). So, if anyone is interested, let me know, and I'll send it to you for verification and testing.

Thanks-

**Comment by LaoZZZZZ** [comment]
Hi there,

Thanks for reporting the issue. Do you mind sharing the dataset with luzhao1986@gmail.com? I will take a look. It has been a couple of years since I last updated this repo. If I recall it correctly, the -d parameter defines the hamming distance between the "centers" of two putative clusters. The center is a consensus sequence of all barcodes within the cluster. The distance among individual barcodes within a cluster could be larger/smaller than the parameter after the algorithm runs multiple iterations.

Lu

**Comment by djross22** [comment]
Lu-
Ok. That makes sense now. A cluster can have barcodes that are distance 6 (or more) from its center because of multiple merging iterations. So, for example, barcode_a with distance 3 from the center of cluster_1 gets merged into cluster_1. Then, cluster_1 gets merged with a larger cluster, cluster_2. The distance between the centers of cluster_1 and cluster_2 is <= d. So, the distance between barcode_a and the center of cluster_2 is <= 2*d.

Did I get that right?

If so, then I don't think there was a problem with the code - just with my understanding of how it works.

Do you still want me to send you an example dataset demonstrating this?

Thanks-
David

**Comment by LaoZZZZZ** [comment]
Yes. That's the right understanding. Closing this issue as it's a WAI behavior
